# Generated by Django 5.0.11 on 2025-05-09 00:09

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.user_directory_path),
        ),
    ]
